//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoGoNecroBotTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDirectory {
            get {
                return ((string)(this["DefaultDirectory"]));
            }
            set {
                this["DefaultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NecroBot.exe")]
        public string NecroBotExeName {
            get {
                return ((string)(this["NecroBotExeName"]));
            }
            set {
                this["NecroBotExeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config.json")]
        public string NecroBotConfigFileName {
            get {
                return ((string)(this["NecroBotConfigFileName"]));
            }
            set {
                this["NecroBotConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultLatitude")]
        public string DefaultLatitudeName {
            get {
                return ((string)(this["DefaultLatitudeName"]));
            }
            set {
                this["DefaultLatitudeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultLongitude")]
        public string DefaultLongitudeName {
            get {
                return ((string)(this["DefaultLongitudeName"]));
            }
            set {
                this["DefaultLongitudeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config")]
        public string NecroBotConfigDirectoryName {
            get {
                return ((string)(this["NecroBotConfigDirectoryName"]));
            }
            set {
                this["NecroBotConfigDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auth.json")]
        public string NecroBotAuthFileName {
            get {
                return ((string)(this["NecroBotAuthFileName"]));
            }
            set {
                this["NecroBotAuthFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logs")]
        public string NecroBotLogsDirectoryName {
            get {
                return ((string)(this["NecroBotLogsDirectoryName"]));
            }
            set {
                this["NecroBotLogsDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NecroBot Release file (*.zip)|*.zip")]
        public string NecroBotReleaseFileExtension {
            get {
                return ((string)(this["NecroBotReleaseFileExtension"]));
            }
            set {
                this["NecroBotReleaseFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dumps")]
        public string NecroBotDumpsDirectoryName {
            get {
                return ((string)(this["NecroBotDumpsDirectoryName"]));
            }
            set {
                this["NecroBotDumpsDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NecroBot-PokeBagStats")]
        public string NecroBotPokeBagStatsFileName {
            get {
                return ((string)(this["NecroBotPokeBagStatsFileName"]));
            }
            set {
                this["NecroBotPokeBagStatsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NAME:")]
        public string DumpName {
            get {
                return ((string)(this["DumpName"]));
            }
            set {
                this["DumpName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lvl:")]
        public string DumpLevel {
            get {
                return ((string)(this["DumpLevel"]));
            }
            set {
                this["DumpLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CP:")]
        public string DumpCp {
            get {
                return ((string)(this["DumpCp"]));
            }
            set {
                this["DumpCp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IV:")]
        public string DumpIv {
            get {
                return ((string)(this["DumpIv"]));
            }
            set {
                this["DumpIv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DumpNameOrder {
            get {
                return ((byte)(this["DumpNameOrder"]));
            }
            set {
                this["DumpNameOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte DumpLevelOrder {
            get {
                return ((byte)(this["DumpLevelOrder"]));
            }
            set {
                this["DumpLevelOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte DumpCpOrder {
            get {
                return ((byte)(this["DumpCpOrder"]));
            }
            set {
                this["DumpCpOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte DumpIvOrder {
            get {
                return ((byte)(this["DumpIvOrder"]));
            }
            set {
                this["DumpIvOrder"] = value;
            }
        }
    }
}
